### ISSUE TITLE
Unable to retrieve CSRF token

### ISSUE THREAD

**Issue by Edeeeeeee** [depthbomb/Scraps#65]
Just click on start button appears this:
[01:04:59] Starting
[01:04:59] "System.Exception: Unable to retrieve CSRF token. Please check your cookie value.
   at Scraps.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Services\RaffleService.cs:line 291
   at Scraps.Services.RaffleService.StartAsync() in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Services\RaffleService.cs:line 165"
[01:04:59] Stopped
[Scraps.2023-07.log](https://github.com/depthbomb/Scraps/files/12190056/Scraps.2023-07.log)

**Comment by depthbomb** [comment]
This issue is because the session cookie name (and value) have been changed. Aside from that, captchas now seem required to enter any raffle.

**Comment by nikkol197** [comment]
Same problem. Can't find scr_session cookie anymore on Edge and Firefox browsers for some reason.

**Comment by Melak1** [comment]
Same problem. Started scraps, got the message saying my cookie was invalid, confused me as I didn't do anything on my end but accepted it and went to update my cookie, can't find the scr token at all.

**Comment by BetaTester704** [comment]
> Aside from that, captchas now seem required to enter any raffle.

Have been able to get into many using pure http requests through Insomnia.
The captchas arent a big issue atm.

**Comment by depthbomb** [comment]
This has been fixed in the latest release.

**Comment by Toltoon45** [comment]
version 5.3.6.0 still the same error
[23:16:12] Starting
[23:16:13] "System.Exception: Unable to retrieve CSRF token. Please check your cookie value.
   at Scraps.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Services\RaffleService.cs:line 291
   at Scraps.Services.RaffleService.StartAsync() in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Services\RaffleService.cs:line 165"
[23:16:13] Stopped

**Comment by 0x2640** [comment]
> version 5.3.6.0 still the same error [23:16:12] Starting [23:16:13] "System.Exception: Unable to retrieve CSRF token. Please check your cookie value. at Scraps.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\Documents\Projects.cs\Scraps\Scraps\Services\RaffleService.cs:line 291 at Scraps.Services.RaffleService.StartAsync() in C:\Users\reese\Documents\Projects.cs\Scraps\Scraps\Services\RaffleService.cs:line 165" [23:16:13] Stopped

are you using the "scraptf" cookie?

**Comment by Toltoon45** [comment]
> > version 5.3.6.0 still the same error [23:16:12] Starting [23:16:13] "System.Exception: Unable to retrieve CSRF token. Please check your cookie value. at Scraps.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\Documents\Projects.cs\Scraps\Scraps\Services\RaffleService.cs:line 291 at Scraps.Services.RaffleService.StartAsync() in C:\Users\reese\Documents\Projects.cs\Scraps\Scraps\Services\RaffleService.cs:line 165" [23:16:13] Stopped
> 
> are you using the "scraptf" cookie?

sorry i used "src session" parameter instead of "scraptf". Now I entered the parameter "scraptf" and everything works fine

**Comment by BetaTester704** [comment]
still doesnt work...
