### ISSUE TITLE
"System.Exception: Unable to retrieve CSRF token. Please check your cookie value.

### ISSUE THREAD

**Issue by krstecd** [depthbomb/Scraps#66]
[17:44:58] Starting
[17:44:59] "System.Exception: Unable to retrieve CSRF token. Please check your cookie value.
   at Scraps.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Services\RaffleService.cs:line 291
   at Scraps.Services.RaffleService.StartAsync() in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Services\RaffleService.cs:line 165"
[17:44:59] Stopped

**Describe the bug**
When i try to start the Scraps it says the error in red that i listed on top. I tried clear my cache, re-entered the scr_session (cookie value) still didnt work.

**To Reproduce**
No idea, yesterday it was working fine.

**Comment by Melak1** [comment]
Same here, for me the the scr_session isn't even appearing anymore.

**Comment by BetaTester704** [comment]
Happens to me as well.

**Comment by depthbomb** [comment]
This has been fixed in the latest release.

**Comment by krstecd** [comment]
> This has been fixed in the latest release.

Ive updated the scraps, still the same problem.

**Comment by krstecd** [comment]
@depthbomb https://imgur.com/a/a3MYu42
The problem is not fixed.

**Comment by krstecd** [comment]
@depthbomb I still have the same problem.
https://i.imgur.com/Y6xUx6N.png
